services:
    db:
        image: postgres:17
        ports:
            - ${DB_PORT}:5432
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - ./postgres-data/db:/var/lib/postgresql/data

volumes:
    postgres_data:
